news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://www.elpais.com
    queries:
      homepage_article_links: '.headline a'
      article_body: ''
      article_title: ''
  elespectador: 
    url: https://www.elespectador.com/noticias/ 
    queries: 
      homepage_article_links: '.node-title.field.field--name-title.field--type-ds.field--label-hidden a' 
      article_body: ''
      article_title: ''
  eltiempo: 
    url: https://www.eltiempo.com/ 
    queries: 
      homepage_article_links: '.title-container a' 
      article_body: ''
      article_title: ''
  semana: 
    url: https://www.semana.com/ 
    queries: 
      homepage_article_links: '.article-h a'
      article_body: ''
      article_title: ''